#+TITLE: PhD Thesis Proposal Summary
#+SUBTITLE: Mechanized Meta-theory for Gradual Security
#+OPTIONS: toc:nil
#+AUTHOR: Tianyu Chen
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage{libertine}

#+MACRO: surface $\lambda_{\mathtt{SEC}}^\star$

In my PhD thesis, I plan to introduce the formal specifications and
present the mechanized meta-theoretic results for a gradual security-typed
programming language called {{{surface}}} in the Agda proof assistant.
The language is /secure/, because its type system and runtime together
ensure the information-flow policy that the output of running a well-typed
{{{surface}}} program does not give out information about its input.
The language is /gradual/, because it gives programmers the choice
between enforcing the aforementioned security policy statically,
when the program type-checks, versus dynamically, when the program
executes. Due to the sensitive nature of information-flow control,
there is strong desire to machine-check (mechanize) the proofs.
Agda is a proof assistant based on a variant of Martin-Löf type theory
(MLTT), which makes sure that all proofs are correct.
